# Change these first
owner: Dennisschu # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Ploen.social
    url: https://Ploen.social
  - name: Ploen.social CDN
    url: https://cdn.Ploen.social
  - name: Dennis.services Matrix
    url: https://matrix.dennis.services
  - name: Teacup
    url: https://teacup.social
  - name: Dennis Blog
    url: https://Dennisschuster.eu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.dennis.services
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Dashboard
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
